server:
  servlet:
    context-path: /api/v1
  tomcat: 
    mbeanregistry:
      enabled: true

logging:
  file:
    name: /app/logs/application.log
  level:
    root: info
    

spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  application:
    name: hof

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} 
    include:
      - db
      - s3
      - mongo
      - iamport

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DB_URL}:3306/hof?connectTimeout=5000&socketTimeout=10000 
    password: ${DB_PASSWORD}
    hikari:
      data-source-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: hhj8159@gmail.com
    password: xlxd kuoi gmnv pnbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000


      
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
    show-sql: true # SQL 로그 출력
    database-platform: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: ${MONGO_URL}
      username: ${MONGO_USERNAME}
  
iamport:
  api-key: ${IAMPORT_API_KEY}
  api-secret: ${IAMPORT_API_SECRET}
      
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lshwan.hof.domain.entity
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    default-statement-timeout: 30   

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  metrics:
    tags:
      application: hof-spring-boot-app
springdoc:
  api-docs:
    enabled: true   
    path: /api-docs 
  swagger-ui:
    enabled: true   
    path: /swag  
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: hhj8159@gmail.com
    password: xlxd kuoi gmnv pnbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30분