server:
  servlet:
    context-path: /api/v1
spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  application:
    name: hof

  profiles:
    include:
      - db
      - s3

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update # 배포할땐 이렇게하면 망할수 있으니 조심 (배포할때 끄기)
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
    show-sql: true # SQL 로그 출력
    database-platform: org.hibernate.dialect.MariaDBDialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lshwan.hof.domain.entity
  configuration:
    map-underscore-to-camel-case: true

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}

management:
  endpoints:
    web:
      cors:
          allowed-origins:
            - http://hof.lshwan.com
            - https://hof.lshwan.com
      exposure:
        include: '*'
      base-path: /actuator
  metrics:
    tags:
      application: my-spring-boot-app


  # security:
  #   user:
  #     name: user1
  #     password: $2a$10$bQPImkdTdIXi7e1TwyP83e0WIZBpHqUXqUYfc0tp8KMDGq8ZJBZ72
  #     roles:
  #     - USER



