server:
  servlet:
    context-path: /api/v1

  tomcat: #  tomcat 메트릭 설정 on. 톰캣 메트릭은 tomcat. 으로 시작
    mbeanregistry: # 톰캣 메트릭을 모두 사용하려면 다음 옵션을 켜야하며, 옵션을 켜지 않으면 tomcat.session. 관련정보만 노출됩니다
      enabled: true


spring:
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  application:
    name: hof

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local} 
    include:
      - db
      - s3
      - mongo

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://${DB_URL}:3306/hof?connectTimeout=5000&socketTimeout=10000  # ✅ Timeout 설정 추가
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}


      
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
    show-sql: true # SQL 로그 출력
    database-platform: org.hibernate.dialect.MariaDBDialect

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lshwan.hof.domain.entity
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
    aggressive-lazy-loading: false
    default-statement-timeout: 30   

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_REGION}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  metrics:
    tags:
      application: hof-spring-boot-app


  # cors:
  #   allowed-origins: "http://localhost:3000"
  #   allowed-methods: "GET, POST, PUT, DELETE"
  #   allowed-headers: "*"
  #   allow-credentials: true

# jwt:
#   secret: "your-secret-key-here"

  # security:
  #   user:
  #     name: user1
  #     password: $2a$10$bQPImkdTdIXi7e1TwyP83e0WIZBpHqUXqUYfc0tp8KMDGq8ZJBZ72
  #     roles:
  #     - USER



