name: Spring Boot CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOCKER_IMAGE_NAME: sounghan94/hof-0.0.1-snapshot
  AWS_REGION: ap-northeast-2
  EC2_SSH_USER: ubuntu
  PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

jobs:
  build-and-push-docker:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission to Gradle wrapper
      run: chmod +x ./gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.DOCKER_IMAGE_NAME }}:latest

    - name: Login to Docker Hub using Access Token
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push the Docker image
      run: docker push ${{ env.DOCKER_IMAGE_NAME }}:latest


  deploy-to-ec2:

    needs: build-and-push-docker
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ env.EC2_SSH_USER }}
        key: ${{ env.PRIVATE_KEY }}
        script: |
          CONTAINER_NAME="hof-container"
          CONTAINER_ID=$(sudo docker ps -q --filter "publish=8081-8080")

          # Check if container with the same name is running and stop/remove it
          if sudo docker ps -a --format "{{.Names}}" | grep -w "$CONTAINER_NAME"; then
            echo "Stopping and removing existing container: $CONTAINER_NAME"
            sudo docker stop $CONTAINER_NAME
            sudo docker rm $CONTAINER_NAME
          fi
  
          # Pull the latest image
          echo "Pulling the latest Docker image: ${{ env.DOCKER_IMAGE_NAME }}"
          sudo docker pull ${{ env.DOCKER_IMAGE_NAME }}
  
          # Run the new container
          echo "Starting a new container: $CONTAINER_NAME"
          sudo docker run --name $CONTAINER_NAME -d -p 8081:8080 -e TZ=Asia/Seoul ${{ env.DOCKER_IMAGE_NAME }}
